routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});


Route::group(['middleware' => 'localization'], function(){
    Route::get('/', 'WelcomeController@index')->name('welcome');
});


Auth::routes();
Auth::routes(['verify' => true]);





Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin'], 'namespace' => 'Admin'], function(){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::resource('business_area','BusinessAreaController');
    Route::resource('family_product','FamilyProductController');

    Route::resource('product','ProductController');
    Route::group(['prefix' => 'products/images'], function(){
        Route::get('/{product}/index', 'ProductImageController@index')->name('product_images.index'); //listar imagenes
        Route::post('/{product}/store', 'ProductImageController@store')->name('product_images.store'); //almacenar imagenes
        Route::delete('/{product_image}/destroy', 'ProductImageController@destroy')->name('product_images.destroy'); //eliminar imagen
        Route::get('/{product_id}/{image_id}', 'ProductImageController@feature')->name('product_images.feature'); //destacar imagen
    });

    Route::resource('news','NewsController');
    Route::resource('service','ServiceController');

});

//======Contacto
Route::post('message', 'ContactMessageController@send')->name('contact_message.send');
Route::get('contact', function(){
    return view('contact');
})->name('contact');

//======Areas de negocios
Route::get('business_areas/{business_area}', 'BusinessAreaController@show')->name('business_area.show');

//======Familias de productos
Route::get('family_products/{family_product}', 'FamilyProductController@index')->name('family_products.index');

//======Productos
Route::get('products/{product}', 'ProductController@show')->name('product.show');

app/FamilyProduct.php
<?php

namespace App;

use igaster\TranslateEloquent\TranslationTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class FamilyProduct extends Model
{

    use TranslationTrait;

    protected static $translatable = ['name', 'text', 'description'];

    protected $fillable = ['text','description','name','image','active'];

    protected static function boot(){
        parent::boot();
        static::deleting(function(BusinessArea $business_area){
            Storage::disk('public')->delete('images/family_products/'.$business_area->image);
        });
    }

    public function products(){
        return $this->hasMany(Product::class);
    }

    public function make_image_url($family_product_id){
        if($this->image == NULL ){
            return 'storage/images/default/default.jpg';
        }
        return 'storage/images/family_products/'.$family_product_id.'/featured/'.$this->image;
    }


    //accessors
    public function getUrlImageAttribute(){

        if($this->image == NULL){
            return 'storage/images/family_products/default.png';
        }
        return 'storage/images/family_products/'.$this->image;
    }

    //SCOPES
    public function scopeActive($query, $flag){
        return $query->where('active', $flag);
    }
}

app/Service.php
<?php

namespace App;

use igaster\TranslateEloquent\TranslationTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Service extends Model
{
    use TranslationTrait;
    protected static $translatable = ['name', 'text', 'description'];

    protected $fillable = ['image', 'active', 'name', 'text', 'description'];

    protected static function boot(){
        parent::boot();
        static::deleting(function(Service $service){
            Storage::disk('public')->deleteDirectory('images/news/'.$service->id);
        });
    }

    public function make_url($service_id){
        return 'storage/images/services/'.$service_id.'/'.$this->image;
    }

    //SCOPES
    public function scopeActive($query, $flag){
        return $query->where('active', $flag);
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ServiceRequest;
use App\Service;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ServiceController extends Controller
{
    public function index(){
        $services = Service::all();
        return view('admin.services.index')->with(compact('services'));
    }

    public function create(){
        return view('admin.services.create');
    }

    public function store(ServiceRequest $request){

        $success = true;
        DB::beginTransaction();
        try{
            $visible = true;
            if(!$request->has('visible')){
                $visible = false;
            }
            $new_service = Service::create([
                'active' => $visible,
                'name' => [
                    'es' => $request->input('name_es'),
                    'en' => $request->input('name_en')
                ],
                'description' => [
                    'es' => $request->input('description_es'),
                    'en' => $request->input('description_en')
                ],
            ]);

            $dom = new \domdocument();
            $dom->loadHTML('<?xml encoding="utf-8" ?>'.$request->input('text_es'));
            $images_es = $dom->getElementsByTagName('img');
            $short_text_es = $dom->getElementsByTagName('p')->item(0)->textContent;

            $iteration = 0;//esto solo lo hago con la version en español
            $featured_image = null;//esto solo lo hago con la version en español
            foreach($images_es as $k => $image){
                $data = $image->getAttribute('src');
                list($type, $data) = explode(';', $data);
                list(, $data) = explode(',', $data);
                $data = base64_decode($data);

                $fileName = uniqid().$k.'.jpg';
                Storage::disk('public')->put('images/services/'.$new_service->id.'/text_images/'.$fileName, $data);
                $image->removeAttribute('src');
                $image->setAttribute('src', asset('storage/images/services/'.$new_service->id.'/text_images/'.$fileName));
                $featured_image = $fileName; //esto solo lo hago con la version en español
                $iteration++;//esto solo lo hago con la version en español
            }
            $text_es = $dom->saveHTML();


            $dom = new \domdocument();
            $dom->loadHTML('<?xml encoding="utf-8" ?>'.$request->input('text_en'));
            $images_en = $dom->getElementsByTagName('img');
            $short_text_en = $dom->getElementsByTagName('p')->item(0)->textContent;


            foreach($images_en as $k => $image){
                $data = $image->getAttribute('src');
                list($type, $data) = explode(';', $data);
                list(, $data) = explode(',', $data);
                $data = base64_decode($data);

                $fileName = uniqid().$k.'.jpg';
                Storage::disk('public')->put('images/services/'.$new_service->id.'/text_images/'.$fileName, $data);
                $image->removeAttribute('src');
                $image->setAttribute('src', asset('storage/images/services/'.$new_service->id.'/text_images/'.$fileName));
            }
            $text_en = $dom->saveHTML();

            $new_service->update([
                'image' => $featured_image,//esto solo lo hago con la version en español
                'text' => [
                    'es' => $text_es,
                    'en' => $text_en
                ],
                'short_text' => [
                    'es' => $short_text_es,
                    'en' => $short_text_en
                ]
            ]);
        } catch (\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }
        if($success === true){
            DB::commit();
            session()->flash('message', ['type' => 'success', 'text'=>'Servicio registrado correctamente']);
            return redirect(route('service.index'));
        }
        else{
            session()->flash('message', ['type' => 'danger', 'text'=>$success]);
            return back();
        }

    }

    public function edit(Service $service){
        return view('admin.services.edit')->with(compact('service'));
    }

    public function update(ServiceRequest $request, Service $service){
        $success = true;
        DB::beginTransaction();
        try{
            $visible = true;
            if(!$request->has('visible')){
                $visible = false;
            }

            /*===================================================================================================UPDATE ES===*/
            $dom = new \domdocument();
            $dom->loadHTML('<?xml encoding="utf-8" ?>'.$request->input('text_es'));
            $images_es = $dom->getElementsByTagName('img');
            $short_text_es = $dom->getElementsByTagName('p')->item(0)->textContent;
            $iteration = 0;
            foreach($images_es as $k => $image){
                $data = $image->getAttribute('src');
                $image_path = explode('/', $data);
                $name_of_file = array_pop($image_path);

                if(!Storage::exists('images/services/'.$service->id.'/text_images/'.$name_of_file)){
                    list($type, $data) = explode(';', $data);
                    list(, $data) = explode(',', $data);
                    $data = base64_decode($data);
                    $fileName = uniqid().$k.'.jpg';
                    Storage::disk('public')->put('images/services/'.$service->id.'/text_images/'.$fileName, $data);
                    $image->removeAttribute('src');
                    $image->setAttribute('src', asset('storage/images/services/'.$service->id.'/text_images/'.$fileName));
                    if($iteration == 0){
                        $service->update([
                            'image' => $fileName
                        ]);
                    }
                }
                $iteration++;
            }
            $text_es = $dom->saveHTML();
            /*===================================================================================================END UPDATE ES===*/

            /*===================================================================================================UPDATE EN===*/
            $dom = new \domdocument();
            $dom->loadHTML('<?xml encoding="utf-8" ?>'.$request->input('text_en'));
            $images_en = $dom->getElementsByTagName('img');
            $short_text_en = $dom->getElementsByTagName('p')->item(0)->textContent;

            foreach($images_en as $k => $image){
                $data = $image->getAttribute('src');
                $image_path = explode('/', $data);
                $name_of_file = array_pop($image_path);

                if(!Storage::exists('images/services/'.$service->id.'/text_images/'.$name_of_file)){
                    list($type, $data) = explode(';', $data);
                    list(, $data) = explode(',', $data);
                    $data = base64_decode($data);
                    $fileName = uniqid().$k.'.jpg';
                    Storage::disk('public')->put('images/services/'.$service->id.'/text_images/'.$fileName, $data);
                    $image->removeAttribute('src');
                    $image->setAttribute('src', asset('storage/images/services/'.$service->id.'/text_images/'.$fileName));
                }
            }
            $text_en = $dom->saveHTML();
            /*===============================================================================================END UPDATE EN======*/

            $service->update([
                'active' => $visible,
                'name' => [
                    'es' => $request->input('name_es'),
                    'en' => $request->input('name_en')
                ],
                'description' => [
                    'es' => $request->input('description_es'),
                    'en' => $request->input('description_en')
                ],
                'text' => [
                    'es' => $text_es,
                    'en' => $text_en
                ],
                'short_text' => [
                    'es' => $short_text_es,
                    'en' => $short_text_en
                ]
            ]);


        } catch (\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }
        if($success === true){
            DB::commit();
            session()->flash('message', ['type' => 'success', 'text'=>'Servicio actualizado correctamente']);
        }
        else{
            session()->flash('message', ['type' => 'danger', 'text'=>$success]);
        }
        return back();

    }

}

resources/views/admin/services/edit.blade.php
@extends('layouts.admin')

@section('scripts')
    <script>
        $(document).ready(function() {
            $('.summernote').summernote({
                codeviewFilter: false,
                codeviewIframeFilter: false,
                toolbar: [
                    // [groupName, [list of button]]
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    //['font', ['strikethrough', 'superscript', 'subscript']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']],
                ]
            });
        });
    </script>
@endsection
@section('styles')
    <style>
        textarea{
            resize: vertical !important;
        }
    </style>
@endsection

@section('content')

    <div class="content">
        <div class="container-fluid">
            @include('partials.messages.general_messages')
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <form action="{{ route('service.update', ['service' => $service->id]) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card-header card-header-primary">
                                <h4 class="card-title ">{{ __('Editar servicio') }}: {{ $service->name }}</h4>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <h4 class="mb-4">Castellano</h4>
                                        <div class="form-group">
                                            <label for="name_es">{{ __('Nombre') }}</label>
                                            <input type="text" name="name_es" class="form-control" id="name_es" value="{{ old('name_es', $service->translate('es')->name) }}">
                                            @if ($errors->has('name_es'))
                                                <span class="text-danger" role="alert">
                                                <strong>{{ $errors->first('name_es') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        <div class="form-group">
                                            <label for="description_es">{{ __('Descripción') }}</label>
                                            <input id="description_es" type="text" name="description_es" class="form-control" value="{{ old('description_es', $service->translate('es')->description) }}" >
                                            @if ($errors->has('description_es'))
                                                <span class="text-danger" role="alert">
                                                    <strong>{{ $errors->first('description_es') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                        <div class="form-group">
                                            <label for="text_es">{{ __('Texto') }}</label>
                                            <textarea id="text_es" type="text" name="text_es" class="summernote form-control"  >{!!old ('text_es', $service->translate('es')->text) !!}</textarea>
                                            @if ($errors->has('text_es'))
                                                <span class="text-danger" role="alert">
                                                    <strong>{{ $errors->first('text_es') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <h4 class="mb-4">Inglés</h4>
                                        <div class="form-group">
                                            <label for="name_en">{{ __('Nombre') }}</label>
                                            <input type="text" name="name_en" class="form-control" id="name_en" value="{{ old('name_en', $service->translate('en')->name) }}">
                                            @if ($errors->has('name_en'))
                                                <span class="text-danger" role="alert">
                                                <strong>{{ $errors->first('name_en') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        <div class="form-group">
                                            <label for="description_en">{{ __('Descripción') }}</label>
                                            <input id="description_en" type="text" name="description_en" class="form-control" value="{{ old('description_en', $service->translate('en')->description) }}" >
                                            @if ($errors->has('description_en'))
                                                <span class="text-danger" role="alert">
                                                    <strong>{{ $errors->first('description_en') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                        <div class="form-group">
                                            <label for="text_en">{{ __('Texto') }}</label>
                                            <textarea id="text_en" type="text" name="text_en" class="summernote form-control" >{!!old ('text_en', $service->translate('en')->text) !!}</textarea>
                                            @if ($errors->has('text_en'))
                                                <span class="text-danger" role="alert">
                                                    <strong>{{ $errors->first('text_en') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="form row">
                                    <div class="col-md-6">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input @if($service->active) checked @endif name="visible" class="form-check-input" type="checkbox" >
                                                {{ __('Visible') }}
                                                <span class="form-check-sign">
                                                    <span class="check"></span>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                   {{-- <div class="col-md-6">
                                        <div class="row">
                                             <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="image" class="mr-auto">{{ __('Imagen') }}</label>
                                                    <div class="input-group">
                                                        <div class="custom-file">
                                                            <input type="file" class="custom-file-input" id="image" name="image">
                                                            <label class="custom-file-label" for="image">Buscar imagen</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <img class="img-fluid img-thumbnail" src="{{ asset($family_product->url_image) }}" alt="">
                                            </div>
                                        </div>
                                    </div>--}}
                                </div>
                            </div>
                            <div class="card-footer justify-content-start">
                                <a href="{{ route('service.index') }}" class="btn btn-warning">Volver</a>
                                <button type="submit"  class="btn btn-default">{{ __('Actualizar') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="content">
        <div class="container-fluid">
            @include('partials.messages.general_messages')
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('service.create') }}" class="btn btn-success">{{ __('Agregar servicio') }}</a>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">{{ __('navigation.Servicios') }}</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                        <th>
                                            ID
                                        </th>
                                        <th>
                                            {{ __('Nombre') }}
                                        </th>
                                        <th>
                                            {{ __('Creado') }}
                                        </th>
                                        <th>
                                            {{ __('Activo') }}
                                        </th>
                                        <th>
                                            {{ __('Acciones') }}
                                        </th>
                                    </thead>
                                    <tbody>
                                        @forelse($services as $service)
                                            <tr>
                                                <td>
                                                    {{ $service->id }}
                                                </td>
                                                <td>
                                                    {{ $service->name }}
                                                </td>
                                                <td>
                                                    {{ $service->created_at->format('d/m/Y') }}
                                                </td>
                                                <td>
                                                    {{ $service->active }}
                                                </td>
                                                <td>
                                                    <a href="{{ route('service.edit', ['service' => $service->id]) }}"  rel="tooltip" title="{{ __('Editar') }}" class="btn btn-link px-1 text-success px-0 my-0 py-0">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    {{--<a href="{{ route ('product_images.index', ['product'=>$product->id]) }}" rel="tooltip" title="Editar imagenes" class="btn btn-link px-1 text-warning px-0 my-0 py-0">
                                                        <i class="fa fa-image"></i>
                                                    </a>--}}
                                                    <button type="button" data-toggle="modal" data-target="#confirm_{{ $service->id }}" rel="tooltip" title="¿{{ __('Eliminar') }}?" class="btn btn-delete px-1 btn-link text-danger my-0 py-0">
                                                        <i class="fa fa-times"></i>
                                                    </button>
                                                    @include('partials.messages.modal_delete', ['url' => route('service.destroy', ['service'=>$service->id]),
                                                        'item_id' => $service->id,
                                                        'message' => '¿Seguro que quiere eliminar "'.$service->name.'"?'])
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="4"><div class="alert alert-info">{{ __('Ningún servicio definido') }}</div></td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection